describe('Register', () => {
    before(() => {
        cy.request('DELETE', 'http://127.0.0.1:8000/remove/usuario/test_user')
      })
    it('register new user successfully', () => {
        cy.visit('http://localhost:3000')
        cy.contains('Cadastrar').click()
        cy.get('input[name="login"]')
            .type('test_user')
            .should('have.value','test_user')
            .get('input[name="senha"]')
            .type('123456')
            .should('have.value','123456')
            .get('input[name="email"]')
            .type('test_user@test.com')
            .should('have.value','test_user@test.com')
            .get('input[name="nome"]')
            .type('Test User')
            .should('have.value','Test User')
        cy.contains('Cadastrar', ).click()
        cy.contains('Login').should('have.class', 'sc-dkzDqf ksXaKt')
        })
    it('fail to register repeated user', () => {
        cy.visit('http://localhost:3000')
        cy.contains('Cadastrar').click()
        cy.get('input[name="login"]')
            .type('test_user')
            .should('have.value','test_user')
            .get('input[name="senha"]')
            .type('123456')
            .should('have.value','123456')
            .get('input[name="email"]')
            .type('test_user@test.com')
            .should('have.value','test_user@test.com')
            .get('input[name="nome"]')
            .type('Test User')
            .should('have.value','Test User')
        cy.contains('Cadastrar', ).click()
        cy.contains('Já existe um objeto com esse valor').should('exist', 'sc-jSMfEi gKnknu')
    })
    it('login, logout and back to home', () => {
        cy.visit('http://localhost:3000')
        cy.get('input[name="login"]')
            .type('teste')
            .get('input[name="senha"]')
            .type('abc123')
        cy.contains('Login', ).click()
        cy.contains('Logout').click()
        cy.contains('Login').should('exist')
        cy.contains('Cadastrar').should('exist')

    })
    it('create a discipline', () => {
        cy.visit('http://localhost:3000')
        cy.get('input[name="login"]')
            .type('teste')
            .get('input[name="senha"]')
            .type('abc123')
        cy.contains('Login', ).click()
        cy.get('*[class^="sc-iqseJM ixCpQW"]').click()
        cy.get('input[name="nome"]')
        .type('Teste de Software')
        .should('have.value','Teste de Software')
        .get('input[name="professor"]')
        .type('Andre Hora')
        .should('have.value','Andre Hora')
        .get('input[name="sala"]')
        .type('2022')
        .should('have.value','2022')
        .get('input[name="horario"]')
        .type('19h')
        .should('have.value','19h')
        .get('input[name="carga_horaria"]')
        .type('60')
        .should('have.value','60')
        cy.contains('Adicionar').click()

    })
})
