# Generated by Django 3.2.5 on 2021-11-15 20:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('login', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('sala', models.CharField(max_length=50)),
                ('carga_horaria', models.IntegerField(validators=[django.core.validators.MinValueValidator(15)])),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='backendapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('data', models.DateTimeField(auto_now=True)),
                ('conteudos', models.CharField(blank=True, max_length=255)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.disciplina')),
            ],
        ),
    ]
