# Generated by Django 3.2.9 on 2021-11-08 19:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('matricula', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=50)),
                ('sala', models.CharField(max_length=50)),
                ('carga_horaria', models.IntegerField(validators=[django.core.validators.MinValueValidator(15)])),
                ('aluno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateTimeField(auto_now=True)),
                ('conteudo', models.CharField(max_length=255)),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.disciplina')),
            ],
        ),
    ]
